package arquimago.listadecompras;

/**
 * Created by Th on 18/06/2015.
 */
public class BDPop {
    private BD bd;

    public BDPop(BD bd) {
        this.bd = bd;
        Item item = new Item();
        item.setComprar(false);
        item.setNome("Canela"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Pimenta do reino"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Molho de Pimenta"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Ervas Frescas"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Manjericão"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Orégano"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Azeite de Oliva"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Queijo Ralado"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Mostarda"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Catchup"); item.setCategoria(1); bd.inserir(item);
        item.setNome("Sal"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Arroz"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Feijão"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Macarrão"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Farinha de Trigo"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Farinha de Mandioca"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Fermento"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Óleo vegetal"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Creme de leite"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Leite Condesado"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Caldo pronto"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Molho de Tomate"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Extrato de Tomate"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Carne"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Peixe"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Frango"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Carne moída"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Kibe"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Nuggets"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Almondegas"); item.setCategoria(2); bd.inserir(item);
        item.setNome("Café em pó"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Café Solúvel"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Café em capsulas"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Achocolatado"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Leite Caixinha"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Leite em Pó"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Iogurte"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Manteiga"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Requeijão Cremoso"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Geléia"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Adoçante"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Açúcar"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Cereal Matinal"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Barrade Cereais"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Granola"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Pão"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Biscoito Doce"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Biscoito Salgado"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Queijo"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Presunto"); item.setCategoria(3); bd.inserir(item);
        item.setNome("Filtro de Café"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Guardanapos"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Papel-Toalha"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Pano de Prato"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Filme de PVC"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Papel Alumínio"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Palito de Dente"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Sacos para embalar"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Lâmpada"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Velas"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Pilhas"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Fósforos"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Prendedor de roupa"); item.setCategoria(4); bd.inserir(item);
        item.setNome("Maçã"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Laranja"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Banana Prata"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Banana da Terra"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Pera"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Limão"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Uva"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Batata"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Cenoura"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Beterraba"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Alface"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Tomate"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Rúcula"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Alho"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Cebola"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Coentro"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Cebolinha"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Abóbora"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Melancia"); item.setCategoria(5); bd.inserir(item);
        item.setNome("Detergente"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Esponja"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Palhadeaço"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Limpador multiuso"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sabão para lava louça"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sabão em barra"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sabão em pó"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sabão líquido"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Amaciante"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Água Sanitária"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Pano de chão"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Lustra móveis"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Limpa vidro"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sacos de lixo"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Flanela"); item.setCategoria(6); bd.inserir(item);
        item.setNome("Sabonete"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Escova de dente"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Pasta de dente"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Fio dental"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Cotonete"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Shampoo"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Condicionador"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Hidratante"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Desodorante"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Protetor Solar"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Lenços de papel"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Lenços umidecidos"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Papel higiênico"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Algodão"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Curativos"); item.setCategoria(7); bd.inserir(item);
        item.setNome("Água Mineral"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Suco"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Refrigerante"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Chá"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Cerveja"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Vinho"); item.setCategoria(8); bd.inserir(item);
        item.setNome("Ice"); item.setCategoria(8); bd.inserir(item);
    }
}
